services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: videolocker
      MARIADB_USER: vl_user
      MARIADB_PASSWORD: cambia_esta_contra
      MARIADB_ROOT_PASSWORD: cambia_root
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "13306:3306"

  server:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      # redundante pero explícito:
      DATABASE_URL: mysql://vl_user:cambia_esta_contra@db:3306/videolocker
      JWT_SECRET: cambia_este_secreto_fuerte
      PORT: 3000
      MEDIA_DIR: /media/videos
      MEDIA_PHOTOS_DIR: /media/photos
      SERVER_MEDIA_DIR: /external-media
      SHADOW_DATABASE_URL: mysql://shadow:shadow_pass@db:3306/videolocker_shadow
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media:/media
      - /media/1TB/www/html:/external-media:ro
    expose:
      - "3000"
    restart: unless-stopped

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  dbdata:
  media:
